export EDITOR='nvim'
export PATH=$PATH:~/.local/bin/
export PATH=$PATH:~/.local/bin/my-scripts/
export PATH=$PATH:~/.local/bin/my-scripts/parser/
export PATH=$PATH:~/.local/bin/my-scripts/spotify_to_tidal/
export PATH=$PATH:~/.ghcup/bin/
