export EDITOR='nvim'
export PATH=$PATH:~/.local/bin/
export PATH=$PATH:~/.local/bin/scripts/
export PATH=$PATH:~/.local/bin/scripts/parser/
export PATH=$PATH:~/.local/bin/scripts/spotify_to_tidal/
export PATH=$PATH:~/.ghcup/bin/
