# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

HISTSIZE=10000
SAVEHIST=10000

autoload -U compinit
zstyle '*:completion*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)

export EDITOR='nvim'
export PATH=$PATH:~/.local/bin/my-scripts/
export PATH=$PATH:~/.local/bin/my-scripts/parser/
export PATH=$PATH:~/.local/bin/my-scripts/spotify_to_tidal/
export PATH=$PATH:~/.ghcup/bin/

# Functions {{{
mkcd ()
{
  mkdir -p -- "$1" && cd -P -- "$1"
}

rmthis() {
    local current_dir=$(pwd)
    cd .. && rm -rv "$current_dir"
}

function yy() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
  yazi "$@" --cwd-file="$tmp"
  if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
	  cd -- "$cwd"
  fi
  rm -f -- "$tmp"
}

bindkey -s '^o' 'yy\n'
# }}}

# Aliases {{{

alias wifi='nmcli device wifi'
alias datos='nmcli device wifi connect Joaco password joacojoaco'

alias reboot='systemctl reboot'

alias py='python'
alias g++f='g++ -std=gnu++11 -g -O2 -Wconversion -Wshadow -Wall -Wextra -D_GLIBCXX_DEBUG'

# Basic aliases
alias ..='cd ..'
alias ...='cd ../..'
alias rm='rm -v'
# alias cp='cp -v'
alias l='ls --color'
alias la='ls --color --almost-all'

# Files
alias zshedit='nvim ~/.config/zsh/zshrc'
alias zshsource='source ~/.zshrc'

# CLI aliases
alias n='nvim'
alias sn='sudoedit'

alias l='eza '
alias la='eza  -a'
alias ll='eza  -al'
alias lt='eza  -T'

alias tr='trash-put'
alias trr='trash-restore'
alias icat='kitty +kitten icat'
alias p='sudo pacman'
alias sp='sudo pacman'
alias sp='sudo pacman'
alias du='du -sh'
alias df='df -h'
alias sdu='sudo du -sh'
alias keysoup="sudo systemctl restart keyd"
alias usefulfiles="yazi '/home/joaco/SecondBrain/1. Áreas 🛸/Informática/Archivos útiles'"

# Git aliases
alias g='git'
alias gs='git status'
alias ga='git add'
alias gall="git add --all"
alias gc='git commit'
alias gcall="git commit -a -m \"🦎\""
alias gcp="git commit -a -m \"🦎\" && git push"

alias b='bat -p'

alias herramientas='bat "/home/joaco/SecondBrain/1. Áreas 🛸/PKM/Informática/Herramientas linux.md"'
alias comandos='bat "/home/joaco/SecondBrain/1. Áreas 🛸/PKM/Informática/Comandos recurrentes.md"'
# }}}

eval "$(zoxide init zsh)"
source <(fzf --zsh)

if [[ "$OSTYPE" == "darwin"* ]]; then
    source ~/powerlevel10k/powerlevel10k.zsh-theme
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
    source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
else
    echo "Unsupported operating system: $OSTYPE"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
