# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

HISTSIZE=10000
SAVEHIST=10000

autoload -U compinit
zstyle '*:completion*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='nvim'
fi

export PATH=$PATH:~/.local/bin

# Functions {{{
mkcd ()
{
  mkdir -p -- "$1" && cd -P -- "$1"
}

# rmthis ()
# {
#   cd '..' -p && rm -rf -P -- "$1"
# }

lfcd () {
    tmp="$(mktemp)"
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}
bindkey -s '^o' 'lfcd\n'
# }}}

# Aliases {{{

alias py='python'
alias g++f='g++ -std=gnu++11 -g -O2 -Wconversion -Wshadow -Wall -Wextra -D_GLIBCXX_DEBUG'

# Basic aliases
alias ..='cd ..'
alias ...='cd ../..'
alias rm='rm -v'
alias cp='cp -v'
alias l='ls --color'
alias la='ls --color --almost-all'

# Files
alias zshedit='nvim ~/.config/zsh/zshrc'
alias zshsource='source ~/.zshrc'

# CLI aliases
alias n='nvim'
alias sn='sudo nvim'
alias e='exa'
alias ea='exa -a'
alias el='exa -al'
alias et='exa -T'
alias elt='exa -alT'
alias tr='trash-put'
alias trr='trash-restore'
alias icat='kitty +kitten icat'
alias p='sudo pacman'
alias sp='sudo pacman'
alias du='du -sh'
alias df='df -h'
alias sudodu='sudo du -sh'
alias sudodf='sudo df -h'
alias keysoup="sudo systemctl restart keyd"

# Git aliases
alias g='git'
alias gs='git status'
alias ga='git add'
alias gall="git add --all"
alias gc='git commit'
alias gcall="git commit -a -m \"🦎\""
alias gcp="git commit -a -m \"🦎\" && git push"

alias b='bat -p'

alias herramientas='bat "/home/joaco/SecondBrain/1. Áreas 🛸/PKM/Informática/Herramientas linux.md"'
alias comandos='bat "/home/joaco/SecondBrain/1. Áreas 🛸/PKM/Informática/Comandos recurrentes.md"'
# }}}

eval "$(zoxide init zsh)"

if [[ "$OSTYPE" == "darwin"* ]]; then
    # deletes file's last line
    sed -i '' '$d' ~/.config/kitty/kitty.conf
    echo "font_size 20" >> ~/.config/kitty/kitty.conf 

    source /usr/local/share/powerlevel10k/powerlevel10k.zsh-theme
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then

    # deletes file's last line
    sed -i '$d' ~/.config/kitty/kitty.conf
    echo "font_size 16" >> ~/.config/kitty/kitty.conf 

    source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
    source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
else
    echo "Unsupported operating system: $OSTYPE"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
